
START_POPULATION={}
START_POPULATION[1]=6
START_POPULATION[2]=6
START_POPULATION[3]=8

START_RESOURCES={}
START_RESOURCES[1]={fat=10,protein=10,carbs=10}
START_RESOURCES[2]={fat=400,protein=400,carbs=400}
START_RESOURCES[3]={fat=400,protein=400,carbs=400}

START_STORAGE={}
START_STORAGE[1]=1300
START_STORAGE[2]=1300
START_STORAGE[3]=3000

function setStartingResources(level)
	print("setting resources to level "..level)
	FAT=START_RESOURCES[level].fat
	PROTEIN=START_RESOURCES[level].protein
	CARBS=START_RESOURCES[level].carbs
	
	TOTAL_STORAGE=PROTEIN+FAT+CARBS
	
	MAX_STORAGE=START_STORAGE[level]
	
	TOTAL_POPULATION=START_POPULATION[level]
end

STORAGE_INCREASE=300
HOUSING_INCREASE=5

MAX_STORAGE=1300


MAX_POPULATION=25

PROTEIN=400

FAT=400
CARBS=400

TOTAL_STORAGE=PROTEIN+FAT+CARBS
TOTAL_POPULATION=0



CARB_EXTRACTORS_MADE=0
PROTEIN_EXTRACTORS_MADE=0
FAT_EXTRACTORS_MADE=0
