


HUDButtons={}


BUTTON1="hudButton1"
BUTTON2="hudButton2"
BUTTON3="hudButton3"
BUTTON4="hudButton4"
BUTTON5="hudButton5"
BUTTON6="hudButton6"
BUTTON7="hudButton7"
BUTTON8="hudButton8"
BUTTON9="hudButton9"

PRODUCTION_BUTTON1="productionButton1"
PRODUCTION_BUTTON2="productionButton2"
PRODUCTION_BUTTON3="productionButton3"
PRODUCTION_BUTTON4="productionButton4"
PRODUCTION_TITLE="productionTitle"
PRODUCTION_PERCENT="productionPercent"

COST_CARB_ICON="costCarbIcon"
COST_FAT_ICON="costFatIcon"
COST_PROTEIN_ICON="costProteinIcon"

COST_CARB="costCarb"
COST_PROTEIN="costProtein"
COST_FAT="costFat"

UNIT_DESCRIPTION="unitDescription"


NO_BUTTON=""

currentlyHitButton=NO_BUTTON;

displayingError=false
displayingErrorTimeSinceStarted=0
displayingErrorTime=3

local unitWithGUI={}


local releasedSinceLast=true
local currentLayout={}


function init(self)
    
   --register all buttons
   addButton(BUTTON1)
   addButton(BUTTON2)
   addButton(BUTTON3)
   addButton(BUTTON4)
   addButton(BUTTON5)
   addButton(BUTTON6)
   addButton(BUTTON7)
   addButton(BUTTON8)
   addButton(BUTTON9)
   
   addButton(PRODUCTION_BUTTON1)
   addButton(PRODUCTION_BUTTON2)
   addButton(PRODUCTION_BUTTON3)
   addButton(PRODUCTION_BUTTON4)
   
   hideUnitCostAndDesc()
       
end


function showUnitCostAndDesc()
   showNode(COST_CARB_ICON)
   showNode(COST_FAT_ICON)
   showNode(COST_PROTEIN_ICON)
   
   showNode(COST_CARB)
   showNode(COST_PROTEIN)
   showNode(COST_FAT)
   
   showNode(UNIT_DESCRIPTION)
end

function hideUnitCostAndDesc()
   hideNode(COST_CARB_ICON)
   hideNode(COST_FAT_ICON)
   hideNode(COST_PROTEIN_ICON)
   
   hideNode(COST_CARB)
   hideNode(COST_PROTEIN)
   hideNode(COST_FAT)
   
   hideNode(UNIT_DESCRIPTION)
end

function displayNodesOnHover(nodesToDisplay)

	if nodesToDisplay then
		if nodesToDisplay.price and nodesToDisplay.description then
			showUnitCostAndDesc()
			setCarbPrice(nodesToDisplay.price.carb)
			setProteinPrice(nodesToDisplay.price.protein)
			setFatPrice(nodesToDisplay.price.fat)
			setUnitDescription(nodesToDisplay.description,nodesToDisplay.name)
		elseif nodesToDisplay.description then
			showNode(UNIT_DESCRIPTION)
			setUnitDescription(nodesToDisplay.description,nodesToDisplay.name)
		else
			hideUnitCostAndDesc()
		end
	else
		hideUnitCostAndDesc()
	end

end



function update(self, dt)
    
    local selectionTextNew=""
    local foundSelectedWithGUI=false
    
    updateResourcesLabels()
    


	if displayingError then
		if displayingErrorTimeSinceStarted<displayingErrorTime then
			displayingErrorTimeSinceStarted=displayingErrorTimeSinceStarted+dt
		else
			displayingError=false
			displayingErrorTimeSinceStarted=0
			displayingErrorTime=3
		end
	else
		gui.set_text(gui.get_node("errorText"), "")
	end

    local selectedUnitsNumberLookup={}
    
    local selectedUnits=0
    
    for unit,stillHere in pairs(SELECTED_UNITS) do 
    
    	if stillHere and unit and ALIVE[unit.id] then
    	
    		if selectedUnitsNumberLookup[unit.name]==nil then
    			selectedUnitsNumberLookup[unit.name]=0
    		end
    		
    		selectedUnitsNumberLookup[unit.name]=selectedUnitsNumberLookup[unit.name]+1
    		
    		if unit.requiresGUI then
    			unitWithGUI=unit
    		end
    		
    		selectedUnits=selectedUnits+1
    	end
    end
    
   if self.selectionText == nil then
   	   self.selectionText = gui.get_node("selectionText")
   end
   
   local selectionNewText=""
   for unitName, numberSelected in pairs(selectedUnitsNumberLookup) do
		selectionNewText=selectionNewText.."\n"..numberSelected.." "..unitName
   end
	
   gui.set_text(self.selectionText,selectionNewText)	
   
   if unitWithGUI.producer then
   		showProductionSection()
   		updateProductionPercentage()
   else
   		hideProductionSection()
   end
   
   applyGUILayout(unitWithGUI.GUILayout)
   
   
   currentLayout=unitWithGUI.GUILayout
   

	if selectedUnits<=0 then
   		hideEverything()
	end
end

function updateResourcesLabels()
	gui.set_text(gui.get_node("proteinText"), math.floor(PROTEIN).." protein")
	gui.set_text(gui.get_node("fatText"), math.floor(FAT).." fat")
	gui.set_text(gui.get_node("carbsText"), math.floor(CARBS).." carbs.")
end


function hideProductionSection()
   hideButton(PRODUCTION_BUTTON1)
   hideButton(PRODUCTION_BUTTON2)
   hideButton(PRODUCTION_BUTTON3)
   hideButton(PRODUCTION_BUTTON4)
   hideNode(PRODUCTION_TITLE)
   hideNode(PRODUCTION_PERCENT)
end

function showProductionSection()

	local producer=unitWithGUI

   
	local numToProduce = table.getn(producer.toProduce)

	if numToProduce>= 1 then
   		showButton(PRODUCTION_BUTTON1)
   		setIconForButton(PRODUCTION_BUTTON1,ICONS[unitWithGUI.currentlyProducingItem])
   	else
   		hideButton(PRODUCTION_BUTTON1)
   	end
   	if numToProduce>=2 then
   		showButton(PRODUCTION_BUTTON2)
   		setIconForButton(PRODUCTION_BUTTON2,ICONS[unitWithGUI.currentlyProducingItem])
   	else
   		hideButton(PRODUCTION_BUTTON2)
   	end
   	if numToProduce>=3 then
   		showButton(PRODUCTION_BUTTON3)
   		setIconForButton(PRODUCTION_BUTTON3,ICONS[unitWithGUI.currentlyProducingItem])
   	else
   		hideButton(PRODUCTION_BUTTON3)
   	end
   	if numToProduce>=4 then
   		showButton(PRODUCTION_BUTTON4)
   		setIconForButton(PRODUCTION_BUTTON4,ICONS[unitWithGUI.currentlyProducingItem])
   	else
   		hideButton(PRODUCTION_BUTTON4)
   	end
   	
   	showNode(PRODUCTION_TITLE)
   	showNode(PRODUCTION_PERCENT)
   	
   	if unitWithGUI.producer and string.len(unitWithGUI.currentlyProducingItem)>0 then
   		gui.set_text(gui.get_node(PRODUCTION_TITLE),"Making "..unitWithGUI.currentlyProducingItem)
   	else	
   		gui.set_text(gui.get_node(PRODUCTION_TITLE),"")
   	end
   	
end

function setIconForButton(buttonId,iconId)

	if iconId and buttonId then
		gui.set_texture(gui.get_node(buttonId.."/icon"), "gui")
		gui.play_flipbook(gui.get_node(buttonId.."/icon"), iconId)
	end
	
end

function updateProductionPercentage()
	if unitWithGUI.currentProductionProgress>0 then
		gui.set_text(gui.get_node(PRODUCTION_PERCENT),math.floor(unitWithGUI.currentProductionProgress*100).." %")
	else
		hideNode(PRODUCTION_PERCENT)
	end
end


function applyGUILayout(layout)
	if layout then
		if layout.button1 then
			showButtonWithIcon(BUTTON1,layout.button1.icon)
			
		else
			hideButton(BUTTON1)
		end
		
		if layout.button2 then	
			showButtonWithIcon(BUTTON2,layout.button2.icon)
			showButton(BUTTON2)
		else
			hideButton(BUTTON2)
		end
		
		if layout.button3 then
			showButtonWithIcon(BUTTON3,layout.button3.icon)
			showButton(BUTTON3)
		else
			hideButton(BUTTON3)
		end
		
		if layout.button4 then
			showButtonWithIcon(BUTTON4,layout.button4.icon)
			showButton(BUTTON4)
		else
			hideButton(BUTTON4)
		end
		
		if layout.button5 then
			showButtonWithIcon(BUTTON5,layout.button5.icon)
			showButton(BUTTON5)
		else
			hideButton(BUTTON5)
		end
		
		if layout.button6 then
			showButtonWithIcon(BUTTON6,layout.button6.icon)
			showButton(BUTTON6)
		else
			hideButton(BUTTON6)
		end
		
		if layout.button7 then
			showButtonWithIcon(BUTTON7,layout.button7.icon)
			showButton(BUTTON7)
		else
			hideButton(BUTTON7)
		end
		
		if layout.button8 then
			showButtonWithIcon(BUTTON8,layout.button8.icon)
			showButton(BUTTON8)
		else
			hideButton(BUTTON8)
		end
		
		if layout.button9 then
			showButtonWithIcon(BUTTON9,layout.button9.icon)
			showButton(BUTTON9)
		else
			hideButton(BUTTON9)
		end
	else
		hideButton(BUTTON1)
		hideButton(BUTTON2)
		hideButton(BUTTON3)
		hideButton(BUTTON4)
		hideButton(BUTTON5)
		hideButton(BUTTON6)
		hideButton(BUTTON7)
		hideButton(BUTTON8)
		hideButton(BUTTON9)
		
	end
end

function checkIfAnyButtonClicked(action,action_id)

	--check if hovered

	local hoverAtLeastOne=false
	for _,buttonObject in  pairs(HUDButtons) do 
	
		if buttonObject.visible then
			local id=buttonObject.id
			--check if click is inside the button
			if isButtonHit(action,id) then
				--send the id to the handler of the click
				handleButtonHovered(id)
				hoverAtLeastOne=true
			end
		end
	end
	
	if hoverAtLeastOne==false then hideUnitCostAndDesc() end
	
	--check if clicked
	
	if action.pressed and action_id==hash("leftClicked") and releasedSinceLast then
	
		GUI_CLICKED=false
		
		--go through all buttons on the HUD 
		releasedSinceLast=false
		for _,buttonObject in  pairs(HUDButtons) do 
		
			local id=buttonObject.id
			--check if click is inside the button
			if isButtonHit(action,id) and buttonObject.visible then
				GUI_CLICKED=true
				highlightButton(id)
				currentlyHitButton=id
				--send the id to the handler of the click
				handleButtonClicked(id)
			end
		end
	--if released, just dehighlight the current button 
	elseif action.released then
		releasedSinceLast=true
		dehighlightButton(currentlyHitButton)
		currentlyHitButton=NO_BUTTON
	end
end

function handleButtonClicked(id) 

	if id==BUTTON1 then
		currentLayout.button1.action()
	elseif id==BUTTON2 then
		currentLayout.button2.action()
	elseif id==BUTTON3 then
		currentLayout.button3.action()
	elseif id==BUTTON4 then
		currentLayout.button4.action()
	elseif id==BUTTON5 then
		currentLayout.button5.action()
	elseif id==BUTTON6 then
		currentLayout.button6.action()
	elseif id==BUTTON7 then
		currentLayout.button7.action()
	elseif id==BUTTON8 then
		currentLayout.button8.action()
	elseif id==BUTTON9 then
		currentLayout.button9.action()
	elseif id==PRODUCTION_BUTTON1 then
		
		currentLayout.productionButton1.action(unitWithGUI)
	elseif id==PRODUCTION_BUTTON2 then
		currentLayout.productionButton2.action(unitWithGUI)
	elseif id==PRODUCTION_BUTTON3 then
		currentLayout.productionButton3.action(unitWithGUI)
	elseif id==PRODUCTION_BUTTON4 then
		currentLayout.productionButton4.action(unitWithGUI)
	end
	
end


function handleButtonHovered(id) 

	--each hover() returns an object telling which objects to display on hover
	
	if id==BUTTON1 then
		displayNodesOnHover(currentLayout.button1.hover())
	elseif id==BUTTON2 then
		displayNodesOnHover(currentLayout.button2.hover())
	elseif id==BUTTON3 then
		displayNodesOnHover(currentLayout.button3.hover())
	elseif id==BUTTON4 then
		displayNodesOnHover(currentLayout.button4.hover())
	elseif id==BUTTON5 then
		displayNodesOnHover(currentLayout.button5.hover())
	elseif id==BUTTON6 then
		displayNodesOnHover(currentLayout.button6.hover())
	elseif id==BUTTON7 then
		displayNodesOnHover(currentLayout.button7.hover())
	elseif id==BUTTON8 then
		displayNodesOnHover(currentLayout.button8.hover())
	elseif id==BUTTON9 then
		displayNodesOnHover(currentLayout.button9.hover())
	elseif id==PRODUCTION_BUTTON1 then
		displayNodesOnHover(currentLayout.productionButton1.hover())
	elseif id==PRODUCTION_BUTTON2 then
		displayNodesOnHover(currentLayout.productionButton2.hover())
	elseif id==PRODUCTION_BUTTON3 then
		displayNodesOnHover(currentLayout.productionButton3.hover())
	elseif id==PRODUCTION_BUTTON4 then
		displayNodesOnHover(currentLayout.productionButton4.hover())
	end
	
end


function final(self)
    -- Add finalization code here
    -- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
    -- Add message-handling code here
    -- Remove this function if not needed
    
    if message_id==hash("newInput") then
		checkIfAnyButtonClicked(message.action,message.action_id)
	elseif message_id==hash("unitDestroyed")then
		if unitWithGUI then
			if unitWithGUI.id==message.id then
				unitWithGUI={}
			end
		else
			unitWithGUI={}
		end
	elseif message_id==hash("displayErrorMessage")then
		--errorText
		displayingError=true
		displayingErrorTimeSinceStarted=0
		gui.set_text(gui.get_node("errorText"), message.text)
	end
end



function on_reload(self)
    -- Add input-handling code here
    -- Remove this function if not needed
end


--helper methods for button management

function addButton(id)
	HUDButtons[id]={id=id,visible=false}
	hideButton(id)
end

function getButtonBounds(id)

	
	local boxNode=gui.get_node(id.."/box")
	local pos=gui.get_position(boxNode)
	local size=gui.get_size(boxNode)
	
	local Xmin = pos.x
	local Ymin = pos.y
	local Xmax = pos.x+size.x
	local Ymax = pos.y+size.y
	
	return {Xmin,Xmax,Ymin,Ymax}
end

function isButtonHit(action,id)

	
	if ((action.x > getButtonBounds(id)[1] and action.x < getButtonBounds(id)[2]) and 
		(action.y > getButtonBounds(id)[3] and action.y < getButtonBounds(id)[4])) then
    	return true
	end
	
	return false
end

function hideButton(id)
   gui.set_color(gui.get_node(id.."/text"), vmath.vector4(0, 0, 0, 0))
   gui.set_color(gui.get_node(id.."/box"), vmath.vector4(0, 0, 0, 0))
   gui.set_color(gui.get_node(id.."/icon"), vmath.vector4(1, 1, 1, 0))
   
   HUDButtons[id]={id=id,visible=false}
end

--not highlighting cuz it overrides in update each loop

function highlightButton(id)
	
	if(id~=NO_BUTTON)then
		gui.set_color(gui.get_node(id.."/box"), vmath.vector4(0, 1, 0, 1))
	end
end

function dehighlightButton(id)
	if(id~=NO_BUTTON)then
		gui.set_color(gui.get_node(id.."/box"), vmath.vector4(1, 0, 0, 1))
	end
end

function showButton(id)
	gui.set_color(gui.get_node(id.."/text"), vmath.vector4(1, 1, 1, 1))
    gui.set_color(gui.get_node(id.."/box"), vmath.vector4(1, 1, 1, 1))
    gui.set_color(gui.get_node(id.."/icon"), vmath.vector4(1, 1, 1, 1))
    
    HUDButtons[id]={id=id,visible=true}
end

function hideNode(id)
	gui.set_color(gui.get_node(id), vmath.vector4(0, 0, 0, 0))
end

function showNode(id)
	gui.set_color(gui.get_node(id), vmath.vector4(1, 1, 1, 1))
end

function showButtonWithIcon(id,icon)
	showButton(id)
	if icon then
		gui.set_texture(gui.get_node(id.."/icon"), "gui")
		gui.play_flipbook(gui.get_node(id.."/icon"), icon)
	end
end

function setCarbPrice(price)
	gui.set_text(gui.get_node("costCarb"),price)
	
	if price>CARBS then
		gui.set_color(gui.get_node("costCarb"), vmath.vector4(1, 0, 0, 1))
	else
		gui.set_color(gui.get_node("costCarb"), vmath.vector4(1, 1, 1, 1))
	end
end

function setProteinPrice(price)
	gui.set_text(gui.get_node("costProtein"),price)
	
	if price>PROTEIN then
		gui.set_color(gui.get_node("costProtein"), vmath.vector4(1, 0, 0, 1))
	else
		gui.set_color(gui.get_node("costProtein"), vmath.vector4(1, 1, 1, 1))
	end
end

function setFatPrice(price)
	gui.set_text(gui.get_node("costFat"),price)
	
	if price>FAT then
		gui.set_color(gui.get_node("costFat"), vmath.vector4(1, 0, 0, 1))
	else
		gui.set_color(gui.get_node("costFat"), vmath.vector4(1, 1, 1, 1))
	end
end

function setUnitDescription(description,unitName)	
	if unitName and string.len(unitName)>0 then
		description="Build "..unitName.."\n"..description
	end
	gui.set_text(gui.get_node("unitDescription"),description)

end

function hideEverything()
	hideButton(BUTTON1)
		hideButton(BUTTON2)
		hideButton(BUTTON3)
		hideButton(BUTTON4)
		hideButton(BUTTON5)
		hideButton(BUTTON6)
		hideButton(BUTTON7)
		hideButton(BUTTON8)
		hideButton(BUTTON9)
		hideProductionSection()
		hideUnitCostAndDesc()
end
