
require "modules.data.unitData"
require "modules.data.worker"
require "modules.data.fighters"
require "modules.data.tanks"
require "modules.data.healers"
require "modules.data.extractors"
require "modules.data.buildings"
require "modules.data.language"
require "modules.data.upgrades"

require "modules.creations"
require "modules.extractorBase"
require "modules.livingUnit"
require "modules.HUDHelper"
require "modules.resources"
require "modules.productionMethods"
require "modules.workerBase"
require "modules.globals"
require "modules.state"
require "modules.soundHelper"
require "modules.pathfinder"
require "modules.coordinates"
require "modules.unit"
require "modules.movableUnit"
require "modules.pathGenerator"
require "modules.pathFollower"
require "modules.bounds"
require "modules.selectMethods"
require "modules.buildingBase"
require "modules.productionUnit"
require "modules.colors"
require "modules.fogManager"
require "modules.fightingUnit"
require "modules.healingUnit"

require "modules.transactions"

require "modules.storyteller"

require "modules.missions.1.subtitlesLevel1"
require "modules.missions.1.section2"
require "modules.missions.1.section1"
require "modules.missions.1.level1"

function init(self)
    
    --give the global tilemap object to this function (globals.lua) and create
    --a table of nodes that will be used for pathfinding
	populateNodeArray(tilemap)
	
	--msg.post("@system:", "toggle_profile")
	
	self.timeSinceLastStorageUpdate=0
	
end



function update(self, dt)
	updateFoW(dt)
	updateStorage(self,dt)
	
	
	act()
	
	GAME_TIME=GAME_TIME+dt
	--msg.post("HUD","displayErrorMessage",{text=GAME_TIME..", "..dt})
end


function updateStorage(self,dt)

	if self.timeSinceLastStorageUpdate>= 1.0 then
	
		self.timeSinceLastStorageUpdate=0
		
		local proteinIncrease=0
		local carbsIncrease=0
		local fatIncrease=0
		--WORKER_RPM
		
		proteinIncrease=proteinIncrease+(WORKER_RPM/60)*WORKERS_EXTRACTING_PROTEIN
		fatIncrease=fatIncrease+(WORKER_RPM/60)*WORKERS_EXTRACTING_FAT
		carbsIncrease=carbsIncrease+(WORKER_RPM/60)*WORKERS_EXTRACTING_CARB

	
		local newProtein=PROTEIN+proteinIncrease
		local newCarbs=CARBS+carbsIncrease
		local newFat=FAT+fatIncrease
		
		local totalStorage=newProtein+newCarbs+newFat
		
		if totalStorage>MAX_STORAGE then
	
			local diff = totalStorage-MAX_STORAGE
			local totalIncrease=proteinIncrease+carbsIncrease+fatIncrease
			
			newProtein=newProtein-math.ceil(diff*(proteinIncrease/totalStorage))
			newCarbs=newCarbs-math.ceil(diff*(carbsIncrease/totalStorage))
			newFat=newFat-math.ceil(diff*(fatIncrease/totalStorage))
			
			totalStorage=newProtein+newCarbs+newFat
			diff = MAX_STORAGE-totalStorage
			
			if diff>0 then
				if proteinIncrease>0 then
					newProtein=newProtein+diff
				elseif carbsIncrease>0 then
					newCarbs=newCarbs+diff
				elseif fatIncrease>0 then
					newFat=newFat+diff
				end
			end
		end
		
		TOTAL_STORAGE=newProtein+newCarbs+newFat
		
		PROTEIN=newProtein
		CARBS=newCarbs
		FAT=newFat
		
	end
	
	self.timeSinceLastStorageUpdate=self.timeSinceLastStorageUpdate+dt
end


function on_message(self, message_id, message, sender)
    
    --a new unit is single-selected, send message to all units and units that are not the selected one will deselect
	if message_id==hash("unitSelected") then
		for _,unit in  pairs(selectableUnits) do 
		    msg.post(unit,"unitSelected",message)
		end
		
	--send massSelection message to all units, each units will decide if it's in the selection
	elseif message_id==hash("massSelection") then
		for _,unit in  pairs(selectableUnits) do 
			if unit and ALIVE[unit] then
		    	pcall(msg.post,unit,"massSelection",message)
		    end
		end
		
	elseif message_id==hash("massSelectionUrgent")then
		for _,unit in  pairs(selectableUnits) do 
			if unit and ALIVE[unit] then
		    	pcall(msg.post,unit,"massSelectionUrgent",message)
		    end
		end
	
	--double click, select all of a kind on screen	
	elseif message_id==hash("allOnScreenSelectSpecific") then
		
		print("allOnScreenSelectSpecific in manager "..message.name)
	
		for _,unit in  pairs(selectableUnits) do 
			if unit and ALIVE[unit] then
		    	pcall(msg.post,unit,"allOnScreenSelectSpecific",message)
		    end
		end
		
	--send message to all units to deselect all
	elseif message_id==hash("deselectAll")then
		
		for _,unit in  pairs(selectableUnits) do 
			if unit and ALIVE[unit] then
		   		msg.post(unit,"deselect",message)
		   	end
		end
	end
end

function on_input(self, action_id, action)

end

function on_reload(self)
	
end
