


function init(self)
	self.spawnedViruses=0
end

function final(self)

end

function update(self, dt)

end

function on_message(self, message_id, message, sender)
	if message_id == hash("attack") then
		attack(self,message.fromRight)
		print("virus mind recieved message")
	end
	

end	

function attack(self,fromRight)


	
	msg.post(spawnVirus(self),"attack",{fromRight=fromRight})
	msg.post(spawnVirus(self),"attack",{fromRight=fromRight})
	msg.post(spawnVirus(self),"attack",{fromRight=fromRight})
	msg.post(spawnVirus(self),"attack",{fromRight=fromRight})
	msg.post(spawnVirus(self),"attack",{fromRight=fromRight})
	msg.post(spawnVirus(self),"attack",{fromRight=fromRight})
	msg.post(spawnVirus(self),"attack",{fromRight=fromRight})

	
	
end

function spawnVirus(self)
	local pos = go.get_position()
	pos.x=pos.x+math.random(-200, 200)
	pos.y=pos.y+math.random(-200, 200)
	return factory.create("#factory",pos)
end


