


function init(self)
	self.spawnedViruses=0
end

function final(self)

end

function update(self, dt)

end

function on_message(self, message_id, message, sender)
	if message_id == hash("attack") then
		attack(self,message.fromRight,message.attackNumber)
		print("virus mind recieved message")
	end
	

end	

function attack(self,fromRight,attackNumber)

	if LEVEL==2 then
		--easy waves
		if attackNumber<7 then
			msg.post(spawnVirus(self,"#purpleFactory"),"attack",{fromRight=fromRight})
		elseif attackNumber<15 then
			msg.post(spawnVirus(self,"#purpleFactory"),"attack",{fromRight=fromRight})
			msg.post(spawnVirus(self,"#purpleFactory"),"attack",{fromRight=fromRight})
		elseif attackNumber<30 then
			msg.post(spawnVirus(self,"#purpleFactory"),"attack",{fromRight=fromRight})
			msg.post(spawnVirus(self,"#purpleTallFactory"),"attack",{fromRight=fromRight})
	
		elseif attackNumber<50 then
			msg.post(spawnVirus(self,"#purpleRoundFactory"),"attack",{fromRight=fromRight})
			msg.post(spawnVirus(self,"#purpleFactory"),"attack",{fromRight=fromRight})
		elseif attackNumber<60 then
			msg.post(spawnVirus(self,"#purpleRoundFactory"),"attack",{fromRight=fromRight})
			msg.post(spawnVirus(self,"#purpleTallFactory"),"attack",{fromRight=fromRight})
		else
			msg.post(spawnVirus(self,"#purpleRoundFactory"),"attack",{fromRight=fromRight})
			msg.post(spawnVirus(self,"#purpleRoundFactory"),"attack",{fromRight=fromRight})
		end
	elseif LEVEL==3 then
		msg.post(spawnVirus(self,"#cloudyStrong3Factory"),"attack",{fromRight=fromRight})
	end

	
	
end

function spawnVirus(self,fac)
	local pos = go.get_position()
	
	local offset=200
	
	if LEVEL==3 then offset=50 end
	
	pos.x=pos.x+math.random(-offset, offset)
	pos.y=pos.y+math.random(-offset, offset)
	
	return factory.create(fac,pos)
end


