


function init(self)
	tilemapObject=tilemap
	self.go=go
	
	
	self.x=go.get_position().x
	self.y=go.get_position().y
	
	self.initialScale=0.5
	
	self.parseInput=function(self, action_id, action)

	end
	
    initBasicUnit(self,WORKER_NAME,go.get_id())
    initMovableUnit(self)
    initBasicWorker(self)
 
 	self.fogRadius=FOG_RADIUS[self.name]

	self.requiresGUI=true
	
	
	local buildBaseAction=function() msg.post("buildingManager", "newBase", {workerID = self.id}) end
	local deselectAction=function() msg.post("manager","deselectAll",{}) end
	local buildCarbExtractor=function() msg.post("buildingManager", "newCarbExtractor", {workerID = self.id}) end
	local buildFatExtractor=function() msg.post("buildingManager", "newFatExtractor", {workerID = self.id}) end
	local buildProteinExtractor=function() msg.post("buildingManager", "newProteinExtractor", {workerID = self.id}) end
	local buildBarracks=function() msg.post("buildingManager", "newBarracks", {workerID = self.id}) end
	
	
	self.GUILayout={button1={icon="deselectIcon",action=deselectAction, hover=function() return HOVER_LAYOUT[CANCEL_PRODUCTION] end},
					button2=nil,
					button3={icon="proteinExtractorIcon",action=buildBarracks,hover= function() return HOVER_LAYOUT[PROTEIN_EXTRACTOR_NAME] end},
					button4={icon="proteinExtractorIcon",action=buildProteinExtractor,hover= function() return HOVER_LAYOUT[PROTEIN_EXTRACTOR_NAME] end},
					button5={icon="fatExtractorIcon",action=buildFatExtractor, hover=function() return HOVER_LAYOUT[FAT_EXTRACTOR_NAME] end},
					button6={icon="carbExtractorIcon",action=buildCarbExtractor, hover=function() return HOVER_LAYOUT[CARB_EXTRACTOR_NAME] end},
					button7={icon="mainBaseIcon",action=buildBaseAction,hover=function() return HOVER_LAYOUT[BASE_NAME] end},
					button8=nil,
					button9=nil}
					
	self.originalHealth=100
	self.health=100
end


function update(self, dt)

	
	basicUnitUpdate(self,dt,go)
	unitUpdate(self,go,dt)
	workerUpdate(self,go,dt)
    
end







function on_message(self, message_id, message, sender)

	handleSelectMethods(self,go,message_id,message,sender)
	basicUnitMessageHandler(self,go,message_id,message,sender)
	workerMessageHandler(self,go,message_id,message,sender)
	
	if self.canFight then
		fightingUnitMessageHandler(self,go,message_id,message,sender)
	end
	
	if message_id == hash("deleteGO")then
		go.delete(go.get_id())
	end

end

function on_reload(self)
    -- Add reload-handling code here
    -- Remove this function if not needed
end

function final(self)
    -- Add finalization code here
    -- Remove this function if not needed
end


