CAN_PLAY_SOUND_EFFECTS=true --only play one each second
LAST_CAN_PLAY_SOUND_EFFECTS=CAN_PLAY_SOUND_EFFECTS

sinceLastTimeSoundEffects=0

function init(self)
	--
	startSoundscapeMusic()
	startMainBackgroundMusic()
end

function on_message(self, message_id, message, sender)
	
	if message_id == hash("slime") and CAN_PLAY_SOUND_EFFECTS then
		playSoundEffect("slime")
	end
	
end



function update(self, dt)
	checkIfCanPlaySFX(dt)
end


-- -5 angle
-- 55.7 saturation
