


function init(self)

	self.go=go
	
	self.x=go.get_position().x
	self.y=go.get_position().y
	self.willBecomeBuilding=true
	self.initialScale=0.5
	self.constructionScale=0.5
	self.fogRadius=BASE_FOG_RADIUS
	
	self.isProteinExtractor=true
	
	self.willBecomeBuilding=true
	self.factory=factory
	
    initBasicUnit(self,PROTEIN_EXTRACTOR_NAME,go.get_id())
	initBuilding(self,sprite,{startPointFromCenter={x=-1,y=1},width=1,height=0},go)
	
	self.parseInput=function(self, action_id, action)
		
		buildingInput(self,action,action_id)
	end
	
	local buildRedBloodCellAction=function() msg.post("unitManager", "newJeep") end
		self.requiresGUI=true
	local deselectAction=function() msg.post("manager","deselectAll",{}) end
	self.GUILayout={button1={text="Deselect",action=deselectAction},
					button2=nil,
					button3=nil,
					button4=nil,
					button5=nil,
					button6=nil,
					button7=nil,
					button8=nil,
					button9=nil}
					
					
end


function update(self, dt)

	basicUnitUpdate(self,dt,go)
    buildingUpdate(self,dt)
    
    
end



function on_message(self, message_id, message, sender)

	handleSelectMethods(self,go,message_id,message)
	basicUnitMessageHandler(self,go,message_id,message,sender)
	buildingMessageHandler(self,go,message_id,message,sender)
	
	if self.selected then
		CURRENT_PRODUCER_POSITION={x=go.get_position().x,y=go.get_position().y}
	end
	
	if message_id == hash("deleteGO")then
		go.delete(go.get_id())
	end

end

function on_reload(self)
    -- Add reload-handling code here
    -- Remove this function if not needed
end

function final(self)
    -- Add finalization code here
    -- Remove this function if not needed
end


