


function init(self)

	self.go=go
	
	self.x=go.get_position().x
	self.y=go.get_position().y
	
	self.isEvolution=true
	
	self.boundsWidthScale=0.4
	self.boundsHeightScale=0.4
	
	self.initialScale=0.7
	self.constructionScale=0.5
	self.fogRadius=BASE_FOG_RADIUS
	
	self.willBecomeBuilding=true
	self.factory=factory
	self.sprite=sprite
	
	self.isBuilding=true
	
	self.needsWaypoint=true
	
    initBasicUnit(self,EVOLUTION_NAME,go.get_id())
	initBuilding(self,sprite,{startPointFromCenter={x=-1,y=0},width=2,height=0},go)
	initProductionUnit(self)
	
	self.parseInput=function(self, action_id, action)
		
		buildingInput(self,action,action_id)
	end
	
	
	
	self.productionComplete=function(itemName,self)
		productionDone(self,itemName)
	end
	
	self.requiresGUI=true
	
	local deselectAction=function() msg.post("manager","deselectAll",{}) end
	local upgradeHealth=function() queue(self,UPGRADE_HEALTH_NAME) end
	local upgradeCarb=function() queue(self,UPGRADE_MORE_CARB_NAME) end
	local upgradeProtein=function() queue(self,UPGRADE_MORE_PROTEIN_NAME) end
	local upgradeFat=function() queue(self,UPGRADE_MORE_FAT_NAME) end
	local upgradeHealer=function() queue(self,UPGRADE_HEALER_NAME) end
	local upgradeTank=function() queue(self,UPGRADE_TANK_NAME) end
	local upgradeSoldier=function() queue(self,UPGRADE_SOLDIER_NAME) end
	
	self.GUILayout={button1={icon="deselectIcon", action=deselectAction, hover=function() return HOVER_LAYOUT[DESELECT]  end},
					button2=nil,
					button3=nil,
					button4=nil,
					button5=nil,
					button6=nil,
					button7=nil,
					button8=nil,
					button9=nil,
					productionButton1={icon="deselectIcon",action=productionButton1Pressed, hover=function() return HOVER_LAYOUT[CANCEL_PRODUCTION] end},
					productionButton2={icon="deselectIcon",action=productionButton2Pressed, hover=function() return HOVER_LAYOUT[CANCEL_PRODUCTION] end},
					productionButton3={icon="deselectIcon",action=productionButton3Pressed, hover=function() return HOVER_LAYOUT[CANCEL_PRODUCTION] end},
					productionButton4={icon="deselectIcon",action=productionButton4Pressed, hover=function() return HOVER_LAYOUT[CANCEL_PRODUCTION] end}}

	
	self.GUILayoutComplete={button1={icon="deselectIcon", action=deselectAction, hover=function() return HOVER_LAYOUT[DESELECT]  end},
					button2=nil,
					button3={icon="healthUpgradeIcon1", action=upgradeHealth, hover=function() return HOVER_LAYOUT[UPGRADE_HEALTH_NAME] end},
					button4={icon="carbUpgradeIcon1", action=upgradeCarb, hover=function() return HOVER_LAYOUT[UPGRADE_MORE_CARB_NAME] end},
					button5={icon="proteinUpgradeIcon1", action=upgradeProtein, hover=function() return HOVER_LAYOUT[UPGRADE_MORE_PROTEIN_NAME] end},
					button6={icon="fatUpgradeIcon1", action=upgradeFat, hover=function() return HOVER_LAYOUT[UPGRADE_MORE_FAT_NAME] end},
					button7={icon="healUpgradeIcon1", action=upgradeHealer, hover=function() return HOVER_LAYOUT[UPGRADE_HEALER_NAME] end},
					button8={icon="tankUpgradeIcon1", action=upgradeTank, hover=function() return HOVER_LAYOUT[UPGRADE_TANK_NAME] end},
					button9={icon="soldierUpgradeIcon1", action=upgradeSoldier, hover=function() return HOVER_LAYOUT[UPGRADE_SOLDIER_NAME] end},
					productionButton1={icon="deselectIcon",action=productionButton1Pressed, hover=function() return HOVER_LAYOUT[CANCEL_PRODUCTION] end},
					productionButton2={icon="deselectIcon",action=productionButton2Pressed, hover=function() return HOVER_LAYOUT[CANCEL_PRODUCTION] end},
					productionButton3={icon="deselectIcon",action=productionButton3Pressed, hover=function() return HOVER_LAYOUT[CANCEL_PRODUCTION] end},
					productionButton4={icon="deselectIcon",action=productionButton4Pressed, hover=function() return HOVER_LAYOUT[CANCEL_PRODUCTION] end}}
	
end



function update(self, dt)

	basicUnitUpdate(self,dt,go)
    buildingUpdate(self,dt,go)
    updateProductionUnit(self,dt)
    
end

function on_message(self, message_id, message, sender)

	handleSelectMethods(self,go,message_id,message)
	basicUnitMessageHandler(self,go,message_id,message,sender)
	buildingMessageHandler(self,go,message_id,message,sender)
	
	if message_id == hash("deleteGO")then
		go.delete(go.get_id())
	end
	
end





