function init(self)
    -- Add initialization code here
    -- Remove this function if not needed
    
     msg.post("#sprite", "play_animation", {id = hash("anim")})
    
     go.set("#sprite", "scale.y", 0.8)
     go.set("#sprite", "scale.x", 0.8)
    
     particlefx.play("#particlefx")
end

function final(self)
    -- Add finalization code here
    -- Remove this function if not needed
end

function update(self, dt)
    -- Add update code here
    -- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
   if message_id == hash("animation_done") then
        -- start the walk animation
        msg.post("#sprite", "play_animation", {id = hash("anim")})
    end
end

function on_input(self, action_id, action)
    -- Add input-handling code here
    -- Remove this function if not needed
end

function on_reload(self)
    -- Add reload-handling code here
    -- Remove this function if not needed
end
