
function on_message(self, message_id, message, sender)
	
	if message_id == hash("newJeep") then
		local newJeep=factory.create("#jeepFactory",vmath.vector3(CURRENT_PRODUCER_POSITION.x,
												    CURRENT_PRODUCER_POSITION.y-TILE_SIZE,1))
				
		msg.post(msg.url(newJeep), "goHere", {x=CURRENT_PRODUCER_POSITION.x,
												    y=CURRENT_PRODUCER_POSITION.y-TILE_SIZE})
								    
		
	end
	
end

